# Generated by Django 6.0.5 on 2026-05-28 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=200)),
                ('nmc_number', models.CharField(max_length=20, unique=True)),
                ('consultation_fees', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('available_days', models.CharField(default='Mon, Tue, Wed, Thu, Fri', help_text='e.g., Mon,Tue,Wed,Thu,Fri,Sat', max_length=100)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('max_patients_per_day', models.IntegerField(default=30)),
                ('is_available', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinic.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('patient_address', models.CharField(blank=True, max_length=300)),
                ('chief_complaint', models.TextField(blank=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('token_number', models.IntegerField(blank=True, null=True)),
                ('token_display', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('booked', '📋 Booked'), ('called', '📢 Called'), ('serving', '🩺 Serving'), ('served', '✅ Served'), ('no_show', '❌ No Show'), ('cancelled', '🚫 Cancelled')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.doctor')),
            ],
            options={
                'ordering': ['appointment_date', 'token_number'],
            },
        ),
        migrations.CreateModel(
            name='QueueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_token', models.IntegerField(default=0)),
                ('last_called_token', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_open', models.BooleanField(default=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_status', to='clinic.department')),
            ],
        ),
    ]
